### ISSUE TITLE
Improperly aligned response documentation section

### ISSUE THREAD

**Issue by deiteris** [advanced-rest-client/api-responses-document#20]
Why padding is used here? This breaks the alignment with request documentation section and started since https://github.com/advanced-rest-client/api-responses-document/commit/a9cf4a846f449a4840cf81d0d428499dc08a3308. Maybe variables should be added to at least control such behavior or do the alignment on a higher level if necessary instead of doing it inside the lower-level component?
![image](https://user-images.githubusercontent.com/6103913/123552749-329f0480-d780-11eb-8ff2-cb8d199703f5.png)

**Comment by TwoPlusTwoOne** [comment]
This was intentional for nesting to give the perspective of the body "belonging" to the response. But I've logged an internal ticket to add a variable to configure this

**Comment by deiteris** [comment]
>to give the perspective of the body "belonging" to the response

There were no issues with the alignment of the response container in 4.2.0 (and I'm still on this version because of that). Even current alignment is inconsistent.
![image](https://user-images.githubusercontent.com/6103913/129085548-f357b93b-ee72-4157-98ed-32901b83f75d.png)

Why not just to add padding to the `api-response-document` container if you want to manage alignment? Or to `section.response-documentation`?
![image](https://user-images.githubusercontent.com/6103913/129085817-81345e08-3e0a-471f-9615-fd3588ba3312.png)

**Comment by TwoPlusTwoOne** [comment]
I've added variables in #23 to control this. The idea is still to have the content of the response be narrower than the tabs selectors, by default. But it can now be customized. Also removed the margin for the divider so that strange behavior of it being too narrow/offset doesn't happen. Please let me know if this satisfies your use case

**Comment by deiteris** [comment]
While I still find this strange, the solution works and I have no complains :) Closing the issue.
